add Simple_two_layer_model
paesanilab/mbpol_cuda_devel pull request #1
Opened 2017-07-17 22:37 UTC by yazhai

2017-07-19 13:16 UTC, zonca requested changes
very good, a few comments below,
also please remove the ipynb checkpoint and the *.pyc from the PR.

Can you also add to the `README.md` a few details about how you tested this and how the results of Python compare to the results from CUDA?

If you push to your branch, the PR will be automatically upated.

2017-07-19 13:16 UTC, zonca commented on Simple_two_layer_NN_model/README
> +     Currtent implemented contents include:
typo

2017-07-19 13:16 UTC, zonca commented on Simple_two_layer_NN_model/README
> +          - simple fully connecte forward, using cublasSgemv() function
typo

2017-07-19 13:16 UTC, zonca commented on Simple_two_layer_NN_model/README
> +          - simple fully connecte forward, using cublasSgemv() function
can you also add a simple explanation of what the `cublasSgemv` function does?, also for function names on Github it is common to format them with backticks `

2017-07-19 13:16 UTC, zonca commented on Simple_two_layer_NN_model/README
> +          - Activation_ReLU forwards, using cudnnActivationForward() with CUDNN_ACTIVATION_RELU
same here, does the function **create** a layer?

2017-07-27 11:34 UTC, zonca commented
thanks @yazhai ! 

it would be nice to use some more Markdown syntax to make the README file more readable and organized.

see the guide on Github: https://guides.github.com/features/mastering-markdown/

you can create headings and format equations as code in their own line (with 4 initial spaces).
Now I'll read the README more carefully and send you comments on the content.

2017-07-27 11:38 UTC, zonca commented on Simple_two_layer_NN_model/README.md
> +and are input to the CUDA/CUDNN tester as arraies when the file is loaded.
arrays

2017-07-27 11:41 UTC, zonca commented
also the Jupyter Notebook is too big, it has a lot of output, it is difficult to read on Github, can you please remove some output?

2017-07-27 11:43 UTC, zonca commented
awesome job! once you do those quick fixes to README and ipynb, I can merge this in!

2017-07-27 18:28 UTC, yazhai commented
Hello,

The README has been corrected and tested on my side. 
The only problem is, for mathematical expressions, the default markdown does not support Latex style from my browser view.
Meanwhile, the online solutions require external markdown instead of Github's.
So I have to put this part in plain text, but should still be able to read with ease.

Regards,
Yaoguang
2017.07.27

2017-07-27 22:06 UTC, zonca commented
yes, now it looks very good!

2017-07-27 22:06 UTC, merged